### ISSUE TITLE
IMPORT is fine. However it makes the following errors:

### ISSUE THREAD

**Issue by RGX650** [MiddleKD/ComfyUI-productfix#3]
recursive file list on directory C:\AI\COMFYUI\ComfyUI\models\onnx
found 0 files
INPUT_TYPES
[ERROR] An error occurred while retrieving information for the 'ResetModelPatcherCalculateWeight' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'ResetModelPatcherCalculateWeight' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'ApplyLatentInjection' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'ApplyLatentInjection' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'VQLoader' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'VQLoader' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'VQEncoder' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'VQEncoder' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'VQDecoder' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'VQDecoder' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'GetTextMask' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'GetTextMask' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'DetailTransferAdd' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'DetailTransferAdd' has no attribute 'INPUT_TYPES'

[ERROR] An error occurred while retrieving information for the 'DetailTransferLatentAdd' node.
Traceback (most recent call last):
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 415, in get_object_info
    out[x] = node_info(x)
  File "C:\AI\COMFYUI\ComfyUI\server.py", line 393, in node_info
    info['input'] = obj_class.INPUT_TYPES()
AttributeError: type object 'DetailTransferLatentAdd' has no attribute 'INPUT_TYPES'

**Comment by MiddleKD** [comment]
I made a stupid mistake. While commenting using Claude, I was unable to check the omitted code. I will fix it soon. thank you.

**Comment by MiddleKD** [comment]
Fixed. maybe it will work
Thank you for your attention.^^
